version: "3.9"
services:
  web:
    image: bjoernf
    expose:
      - 80
    environment:
      PORT: 80
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: bjoernf.com,web.bjoernf.com
      LETSENCRYPT_HOST: bjoernf.com,web.bjoernf.com
    networks:
      - nginx-proxy
    restart: unless-stopped

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
