name: Recreate Wikipedia Connections

on:
  workflow_dispatch:
  schedule:
    - cron: "5 0 * * *"

jobs:
  create_game:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - name: Run image
        uses: abatilo/actions-poetry@v3

      - name: Install the project dependencies
        working-directory: src/pages/games/wikipedia-connections/data
        run: poetry install --no-root

      - working-directory: src/pages/games/wikipedia-connections/data
        run: poetry run python today.py

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-west-2

      - name: Sync to S3
        working-directory: src/pages/games/wikipedia-connections/data
        run: aws s3 sync . s3://bjoernf.com/dynamic --exclude='*' --include='wikipedia-game.json'
